### ISSUE TITLE
Existing iam role

### ISSUE THREAD

**Issue by pkonneker** [dougmoscrop/add-custom-resource#5]
Is it possible to use an existing iam role with this plugin, or does it require creating a new role altogether?

**Comment by dougmoscrop** [comment]
The current implementation creates a role but I'd wekcome a PR that supports an existing role!

**Comment by dougmoscrop** [comment]
I added support for this in `3.0.0`

(note that 3.0.0 returns a promise rather than being sync, due to using `rollup` for dependency-inlining support)
